version: "3.9"
services:
  db:
    image: postgres:16
    container_name: prashn-db
    restart: always
    environment:
      POSTGRES_DB: prashn
      POSTGRES_USER: beast
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - prashn_data:/var/lib/postgresql/data

volumes:
  prashn_data:
