version: "3.9"
services:
  db:
    image: postgres:18
    container_name: quizify-db
    restart: always
    environment:
      POSTGRES_DB: quizify
      POSTGRES_USER: beast
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql

volumes:
  quizify_data:
